version: '3.8'
services:
  db:
    image: mysql:8.0
    restart: always
    volumes:
      - db-data:/var/lib/postgresql/data
    environment:
      - wqMYSQL_ALLOW_EMPTY_PASSWORD=yes

  web:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/myapp
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    ports:
      - "3000:3000"
    depends_on:
      - db
    environment:
      DATABASE_URL: postgres://your_postgres_user:your_postgres_password@db:5432/your_database_name

volumes:
  db-data: