default: &default
  adapter: mysql2
  encoding: utf8
  pool: 5
  host: localhost
  username: root
  password:
  socket: /var/run/mysqld/mysqld.sock

development:
  <<: *default
  database: helloworld_development

test:
  <<: *default
  database: helloworld_test

production:
  <<: *default
  database: helloworld_production
  username: helloworld
  password: <%= ENV['HELLOWORLD_DATABASE_PASSWORD'] %>